- id: 'high_temperature_alert'
  alias: 'High Temperature Alert'
  description: 'Send notification when temperature exceeds 27°C'
  trigger:
    platform: numeric_state
    entity_id: sensor.esp_temperature
    above: 27
  action:
    service: notify.outlook_notification
    data:
      title: "Temperature Alert"
      message: "Temperature has exceeded 28°C! Current temperature is {{ states('sensor.esp_temperature') }}°C"
